# Generated by Django 2.2.7 on 2019-11-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
